insert into user_data (email, payload, updated_at)
values (
  'demo@gradflow.local',
  jsonb_build_object(
    'goals', jsonb_build_array(
      jsonb_build_object('id', 1, 'userEmail', 'demo@gradflow.local', 'title', 'Stabilize weekly research rhythm', 'category', 'Research', 'targetDate', (current_date + 30)::text, 'progress', 35, 'completed', false),
      jsonb_build_object('id', 2, 'userEmail', 'demo@gradflow.local', 'title', 'Build a sustainable health routine', 'category', 'Health', 'targetDate', (current_date + 45)::text, 'progress', 42, 'completed', false),
      jsonb_build_object('id', 3, 'userEmail', 'demo@gradflow.local', 'title', 'Keep monthly spending under budget', 'category', 'Money', 'targetDate', (current_date + 20)::text, 'progress', 55, 'completed', false),
      jsonb_build_object('id', 4, 'userEmail', 'demo@gradflow.local', 'title', 'Finish course assignment draft', 'category', 'Course', 'targetDate', (current_date + 12)::text, 'progress', 70, 'completed', false)
    ),
    'habits', jsonb_build_array(
      jsonb_build_object('id', 1, 'userEmail', 'demo@gradflow.local', 'name', 'Drink water', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2),
      jsonb_build_object('id', 2, 'userEmail', 'demo@gradflow.local', 'name', 'Exercise', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2),
      jsonb_build_object('id', 3, 'userEmail', 'demo@gradflow.local', 'name', 'Read paper', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 1),
      jsonb_build_object('id', 4, 'userEmail', 'demo@gradflow.local', 'name', 'Budget check', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 3)
    ),
    'rewardItems', jsonb_build_array(
      jsonb_build_object('id', 1, 'userEmail', 'demo@gradflow.local', 'name', 'Coffee break', 'icon', '*', 'pointCost', 4),
      jsonb_build_object('id', 2, 'userEmail', 'demo@gradflow.local', 'name', 'Movie night', 'icon', '*', 'pointCost', 8),
      jsonb_build_object('id', 3, 'userEmail', 'demo@gradflow.local', 'name', 'Bookstore visit', 'icon', '*', 'pointCost', 12)
    ),
    'tasks', jsonb_build_array(
      jsonb_build_object('id', 1, 'userEmail', 'demo@gradflow.local', 'name', 'Annotate related-work paper', 'category', 'Research', 'priority', 5, 'effort', 3, 'deadline', (current_date - 6)::text, 'status', 'DONE', 'createdAt', to_char(current_timestamp - interval '12 day', 'YYYY-MM-DD"T"HH24:MI:SS'), 'updatedAt', to_char(current_timestamp - interval '6 day', 'YYYY-MM-DD"T"HH24:MI:SS'), 'goalId', 1),
      jsonb_build_object('id', 2, 'userEmail', 'demo@gradflow.local', 'name', 'Write experiment setup notes', 'category', 'Research', 'priority', 4, 'effort', 2, 'deadline', (current_date - 3)::text, 'status', 'DONE', 'createdAt', to_char(current_timestamp - interval '9 day', 'YYYY-MM-DD"T"HH24:MI:SS'), 'updatedAt', to_char(current_timestamp - interval '3 day', 'YYYY-MM-DD"T"HH24:MI:SS'), 'goalId', 1),
      jsonb_build_object('id', 3, 'userEmail', 'demo@gradflow.local', 'name', 'Prepare advisor meeting questions', 'category', 'Meeting', 'priority', 4, 'effort', 2, 'deadline', current_date::text, 'status', 'PENDING', 'createdAt', to_char(current_timestamp - interval '2 day', 'YYYY-MM-DD"T"HH24:MI:SS'), 'updatedAt', to_char(current_timestamp - interval '2 day', 'YYYY-MM-DD"T"HH24:MI:SS'), 'goalId', 1),
      jsonb_build_object('id', 4, 'userEmail', 'demo@gradflow.local', 'name', 'Implement baseline comparison', 'category', 'Research', 'priority', 5, 'effort', 4, 'deadline', (current_date + 2)::text, 'status', 'PENDING', 'createdAt', to_char(current_timestamp - interval '1 day', 'YYYY-MM-DD"T"HH24:MI:SS'), 'updatedAt', to_char(current_timestamp - interval '1 day', 'YYYY-MM-DD"T"HH24:MI:SS'), 'goalId', 1),
      jsonb_build_object('id', 5, 'userEmail', 'demo@gradflow.local', 'name', 'Submit course reading response', 'category', 'Course', 'priority', 3, 'effort', 2, 'deadline', (current_date + 1)::text, 'status', 'PENDING', 'createdAt', to_char(current_timestamp - interval '3 day', 'YYYY-MM-DD"T"HH24:MI:SS'), 'updatedAt', to_char(current_timestamp - interval '3 day', 'YYYY-MM-DD"T"HH24:MI:SS'), 'goalId', 4),
      jsonb_build_object('id', 6, 'userEmail', 'demo@gradflow.local', 'name', 'Plan next exercise block', 'category', 'Health', 'priority', 3, 'effort', 1, 'deadline', (current_date + 1)::text, 'status', 'PENDING', 'createdAt', to_char(current_timestamp - interval '1 day', 'YYYY-MM-DD"T"HH24:MI:SS'), 'updatedAt', to_char(current_timestamp - interval '1 day', 'YYYY-MM-DD"T"HH24:MI:SS'), 'goalId', 2),
      jsonb_build_object('id', 7, 'userEmail', 'demo@gradflow.local', 'name', 'Reconcile this week expenses', 'category', 'Money', 'priority', 3, 'effort', 1, 'deadline', (current_date + 3)::text, 'status', 'PENDING', 'createdAt', to_char(current_timestamp - interval '4 day', 'YYYY-MM-DD"T"HH24:MI:SS'), 'updatedAt', to_char(current_timestamp - interval '4 day', 'YYYY-MM-DD"T"HH24:MI:SS'), 'goalId', 3),
      jsonb_build_object('id', 8, 'userEmail', 'demo@gradflow.local', 'name', 'Draft intro paragraph', 'category', 'Research', 'priority', 4, 'effort', 3, 'deadline', (current_date + 5)::text, 'status', 'PENDING', 'createdAt', to_char(current_timestamp, 'YYYY-MM-DD"T"HH24:MI:SS'), 'updatedAt', to_char(current_timestamp, 'YYYY-MM-DD"T"HH24:MI:SS'), 'goalId', 1)
    ),
    'dailyLogs', jsonb_build_array(
      jsonb_build_object('id', 1, 'userEmail', 'demo@gradflow.local', 'logDate', (current_date - 13)::text, 'sleepHours', 6.8, 'sleepStart', '00:40:00', 'wakeTime', '07:30:00', 'mood', 3, 'stress', 4, 'studyHours', 2.0, 'waterCups', 6, 'waterMl', 1500, 'exercised', true, 'exerciseType', 'Walk', 'exerciseMinutes', 25, 'note', 'Recovered from a packed meeting day.', 'updatedAt', to_char(current_timestamp - interval '13 day', 'YYYY-MM-DD"T"HH24:MI:SS')),
      jsonb_build_object('id', 2, 'userEmail', 'demo@gradflow.local', 'logDate', (current_date - 12)::text, 'sleepHours', 7.4, 'sleepStart', '00:10:00', 'wakeTime', '07:35:00', 'mood', 4, 'stress', 3, 'studyHours', 3.0, 'waterCups', 8, 'waterMl', 2000, 'exercised', false, 'exerciseType', '', 'exerciseMinutes', 0, 'note', 'Read two papers and made short notes.', 'updatedAt', to_char(current_timestamp - interval '12 day', 'YYYY-MM-DD"T"HH24:MI:SS')),
      jsonb_build_object('id', 3, 'userEmail', 'demo@gradflow.local', 'logDate', (current_date - 11)::text, 'sleepHours', 6.2, 'sleepStart', '01:20:00', 'wakeTime', '07:30:00', 'mood', 2, 'stress', 5, 'studyHours', 1.0, 'waterCups', 5, 'waterMl', 1250, 'exercised', true, 'exerciseType', 'Stretching', 'exerciseMinutes', 15, 'note', 'Low energy, kept the scope small.', 'updatedAt', to_char(current_timestamp - interval '11 day', 'YYYY-MM-DD"T"HH24:MI:SS')),
      jsonb_build_object('id', 4, 'userEmail', 'demo@gradflow.local', 'logDate', (current_date - 10)::text, 'sleepHours', 7.8, 'sleepStart', '23:50:00', 'wakeTime', '07:40:00', 'mood', 4, 'stress', 2, 'studyHours', 3.5, 'waterCups', 9, 'waterMl', 2250, 'exercised', true, 'exerciseType', 'Gym', 'exerciseMinutes', 35, 'note', 'Good focus block after lunch.', 'updatedAt', to_char(current_timestamp - interval '10 day', 'YYYY-MM-DD"T"HH24:MI:SS')),
      jsonb_build_object('id', 5, 'userEmail', 'demo@gradflow.local', 'logDate', (current_date - 9)::text, 'sleepHours', 7.0, 'sleepStart', '00:30:00', 'wakeTime', '07:30:00', 'mood', 3, 'stress', 3, 'studyHours', 2.5, 'waterCups', 7, 'waterMl', 1750, 'exercised', false, 'exerciseType', '', 'exerciseMinutes', 0, 'note', 'Admin tasks took longer than expected.', 'updatedAt', to_char(current_timestamp - interval '9 day', 'YYYY-MM-DD"T"HH24:MI:SS')),
      jsonb_build_object('id', 6, 'userEmail', 'demo@gradflow.local', 'logDate', (current_date - 8)::text, 'sleepHours', 8.1, 'sleepStart', '23:40:00', 'wakeTime', '07:45:00', 'mood', 5, 'stress', 2, 'studyHours', 4.0, 'waterCups', 10, 'waterMl', 2500, 'exercised', true, 'exerciseType', 'Run', 'exerciseMinutes', 30, 'note', 'Finished experiment setup notes.', 'updatedAt', to_char(current_timestamp - interval '8 day', 'YYYY-MM-DD"T"HH24:MI:SS')),
      jsonb_build_object('id', 7, 'userEmail', 'demo@gradflow.local', 'logDate', (current_date - 7)::text, 'sleepHours', 6.6, 'sleepStart', '01:00:00', 'wakeTime', '07:35:00', 'mood', 3, 'stress', 4, 'studyHours', 2.0, 'waterCups', 6, 'waterMl', 1500, 'exercised', false, 'exerciseType', '', 'exerciseMinutes', 0, 'note', 'Needed more breaks between tasks.', 'updatedAt', to_char(current_timestamp - interval '7 day', 'YYYY-MM-DD"T"HH24:MI:SS')),
      jsonb_build_object('id', 8, 'userEmail', 'demo@gradflow.local', 'logDate', (current_date - 6)::text, 'sleepHours', 7.2, 'sleepStart', '00:15:00', 'wakeTime', '07:30:00', 'mood', 4, 'stress', 3, 'studyHours', 3.0, 'waterCups', 8, 'waterMl', 2000, 'exercised', true, 'exerciseType', 'Walk', 'exerciseMinutes', 20, 'note', 'Advisor feedback was actionable.', 'updatedAt', to_char(current_timestamp - interval '6 day', 'YYYY-MM-DD"T"HH24:MI:SS')),
      jsonb_build_object('id', 9, 'userEmail', 'demo@gradflow.local', 'logDate', (current_date - 5)::text, 'sleepHours', 7.6, 'sleepStart', '23:55:00', 'wakeTime', '07:30:00', 'mood', 4, 'stress', 2, 'studyHours', 3.5, 'waterCups', 9, 'waterMl', 2250, 'exercised', true, 'exerciseType', 'Yoga', 'exerciseMinutes', 25, 'note', 'Cleaned up notes and references.', 'updatedAt', to_char(current_timestamp - interval '5 day', 'YYYY-MM-DD"T"HH24:MI:SS')),
      jsonb_build_object('id', 10, 'userEmail', 'demo@gradflow.local', 'logDate', (current_date - 4)::text, 'sleepHours', 5.9, 'sleepStart', '01:35:00', 'wakeTime', '07:30:00', 'mood', 2, 'stress', 5, 'studyHours', 1.0, 'waterCups', 4, 'waterMl', 1000, 'exercised', false, 'exerciseType', '', 'exerciseMinutes', 0, 'note', 'Deadline pressure; need lighter planning.', 'updatedAt', to_char(current_timestamp - interval '4 day', 'YYYY-MM-DD"T"HH24:MI:SS')),
      jsonb_build_object('id', 11, 'userEmail', 'demo@gradflow.local', 'logDate', (current_date - 3)::text, 'sleepHours', 7.3, 'sleepStart', '00:05:00', 'wakeTime', '07:25:00', 'mood', 4, 'stress', 3, 'studyHours', 2.5, 'waterCups', 8, 'waterMl', 2000, 'exercised', true, 'exerciseType', 'Gym', 'exerciseMinutes', 40, 'note', 'Submitted reading response draft.', 'updatedAt', to_char(current_timestamp - interval '3 day', 'YYYY-MM-DD"T"HH24:MI:SS')),
      jsonb_build_object('id', 12, 'userEmail', 'demo@gradflow.local', 'logDate', (current_date - 2)::text, 'sleepHours', 8.0, 'sleepStart', '23:30:00', 'wakeTime', '07:30:00', 'mood', 5, 'stress', 2, 'studyHours', 4.5, 'waterCups', 10, 'waterMl', 2500, 'exercised', true, 'exerciseType', 'Run', 'exerciseMinutes', 30, 'note', 'Strong deep work session.', 'updatedAt', to_char(current_timestamp - interval '2 day', 'YYYY-MM-DD"T"HH24:MI:SS')),
      jsonb_build_object('id', 13, 'userEmail', 'demo@gradflow.local', 'logDate', (current_date - 1)::text, 'sleepHours', 6.7, 'sleepStart', '00:50:00', 'wakeTime', '07:35:00', 'mood', 3, 'stress', 4, 'studyHours', 2.0, 'waterCups', 7, 'waterMl', 1750, 'exercised', false, 'exerciseType', '', 'exerciseMinutes', 0, 'note', 'Blocked on baseline comparison detail.', 'updatedAt', to_char(current_timestamp - interval '1 day', 'YYYY-MM-DD"T"HH24:MI:SS')),
      jsonb_build_object('id', 14, 'userEmail', 'demo@gradflow.local', 'logDate', current_date::text, 'sleepHours', 7.5, 'sleepStart', '00:00:00', 'wakeTime', '07:30:00', 'mood', 4, 'stress', 3, 'studyHours', 1.5, 'waterCups', 8, 'waterMl', 2000, 'exercised', true, 'exerciseType', 'Walk', 'exerciseMinutes', 20, 'note', 'Seed check-in for first launch.', 'updatedAt', to_char(current_timestamp, 'YYYY-MM-DD"T"HH24:MI:SS'))
    ),
    'habitRecords', jsonb_build_array(
      jsonb_build_object('id', 1, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 1, 'name', 'Drink water', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2), 'recordDate', (current_date - 13)::text, 'count', 1),
      jsonb_build_object('id', 2, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 3, 'name', 'Read paper', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 1), 'recordDate', (current_date - 13)::text, 'count', 1),
      jsonb_build_object('id', 3, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 1, 'name', 'Drink water', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2), 'recordDate', (current_date - 12)::text, 'count', 1),
      jsonb_build_object('id', 4, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 3, 'name', 'Read paper', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 1), 'recordDate', (current_date - 12)::text, 'count', 1),
      jsonb_build_object('id', 5, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 4, 'name', 'Budget check', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 3), 'recordDate', (current_date - 12)::text, 'count', 1),
      jsonb_build_object('id', 6, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 1, 'name', 'Drink water', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2), 'recordDate', (current_date - 11)::text, 'count', 1),
      jsonb_build_object('id', 7, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 2, 'name', 'Exercise', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2), 'recordDate', (current_date - 11)::text, 'count', 1),
      jsonb_build_object('id', 8, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 1, 'name', 'Drink water', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2), 'recordDate', (current_date - 10)::text, 'count', 1),
      jsonb_build_object('id', 9, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 2, 'name', 'Exercise', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2), 'recordDate', (current_date - 10)::text, 'count', 1),
      jsonb_build_object('id', 10, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 3, 'name', 'Read paper', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 1), 'recordDate', (current_date - 10)::text, 'count', 1),
      jsonb_build_object('id', 11, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 1, 'name', 'Drink water', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2), 'recordDate', (current_date - 9)::text, 'count', 1),
      jsonb_build_object('id', 12, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 4, 'name', 'Budget check', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 3), 'recordDate', (current_date - 9)::text, 'count', 1),
      jsonb_build_object('id', 13, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 1, 'name', 'Drink water', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2), 'recordDate', (current_date - 8)::text, 'count', 1),
      jsonb_build_object('id', 14, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 2, 'name', 'Exercise', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2), 'recordDate', (current_date - 8)::text, 'count', 1),
      jsonb_build_object('id', 15, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 3, 'name', 'Read paper', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 1), 'recordDate', (current_date - 8)::text, 'count', 1),
      jsonb_build_object('id', 16, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 1, 'name', 'Drink water', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2), 'recordDate', (current_date - 7)::text, 'count', 1),
      jsonb_build_object('id', 17, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 1, 'name', 'Drink water', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2), 'recordDate', (current_date - 6)::text, 'count', 1),
      jsonb_build_object('id', 18, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 2, 'name', 'Exercise', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2), 'recordDate', (current_date - 6)::text, 'count', 1),
      jsonb_build_object('id', 19, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 3, 'name', 'Read paper', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 1), 'recordDate', (current_date - 6)::text, 'count', 1),
      jsonb_build_object('id', 20, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 1, 'name', 'Drink water', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2), 'recordDate', (current_date - 5)::text, 'count', 1),
      jsonb_build_object('id', 21, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 2, 'name', 'Exercise', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2), 'recordDate', (current_date - 5)::text, 'count', 1),
      jsonb_build_object('id', 22, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 4, 'name', 'Budget check', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 3), 'recordDate', (current_date - 5)::text, 'count', 1),
      jsonb_build_object('id', 23, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 1, 'name', 'Drink water', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2), 'recordDate', (current_date - 4)::text, 'count', 1),
      jsonb_build_object('id', 24, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 1, 'name', 'Drink water', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2), 'recordDate', (current_date - 3)::text, 'count', 1),
      jsonb_build_object('id', 25, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 2, 'name', 'Exercise', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2), 'recordDate', (current_date - 3)::text, 'count', 1),
      jsonb_build_object('id', 26, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 3, 'name', 'Read paper', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 1), 'recordDate', (current_date - 3)::text, 'count', 1),
      jsonb_build_object('id', 27, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 1, 'name', 'Drink water', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2), 'recordDate', (current_date - 2)::text, 'count', 1),
      jsonb_build_object('id', 28, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 2, 'name', 'Exercise', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2), 'recordDate', (current_date - 2)::text, 'count', 1),
      jsonb_build_object('id', 29, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 3, 'name', 'Read paper', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 1), 'recordDate', (current_date - 2)::text, 'count', 1),
      jsonb_build_object('id', 30, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 4, 'name', 'Budget check', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 3), 'recordDate', (current_date - 2)::text, 'count', 1),
      jsonb_build_object('id', 31, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 1, 'name', 'Drink water', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2), 'recordDate', (current_date - 1)::text, 'count', 1),
      jsonb_build_object('id', 32, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 3, 'name', 'Read paper', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 1), 'recordDate', (current_date - 1)::text, 'count', 1),
      jsonb_build_object('id', 33, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 1, 'name', 'Drink water', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2), 'recordDate', current_date::text, 'count', 1),
      jsonb_build_object('id', 34, 'userEmail', 'demo@gradflow.local', 'habit', jsonb_build_object('id', 2, 'name', 'Exercise', 'targetCount', 1, 'unit', 'check', 'icon', '*', 'goalId', 2), 'recordDate', current_date::text, 'count', 1)
    ),
    'expenses', jsonb_build_array(
      jsonb_build_object('id', 1, 'userEmail', 'demo@gradflow.local', 'expenseDate', (current_date - 13)::text, 'category', 'Food', 'type', 'EXPENSE', 'amount', 180, 'description', 'Lunch box'),
      jsonb_build_object('id', 2, 'userEmail', 'demo@gradflow.local', 'expenseDate', (current_date - 12)::text, 'category', 'Coffee', 'type', 'EXPENSE', 'amount', 85, 'description', 'Cafe study block'),
      jsonb_build_object('id', 3, 'userEmail', 'demo@gradflow.local', 'expenseDate', (current_date - 11)::text, 'category', 'Transport', 'type', 'EXPENSE', 'amount', 40, 'description', 'Bus to campus'),
      jsonb_build_object('id', 4, 'userEmail', 'demo@gradflow.local', 'expenseDate', (current_date - 10)::text, 'category', 'Books', 'type', 'EXPENSE', 'amount', 620, 'description', 'Research methods book'),
      jsonb_build_object('id', 5, 'userEmail', 'demo@gradflow.local', 'expenseDate', (current_date - 9)::text, 'category', 'Scholarship', 'type', 'INCOME', 'amount', 8000, 'description', 'Monthly scholarship'),
      jsonb_build_object('id', 6, 'userEmail', 'demo@gradflow.local', 'expenseDate', (current_date - 8)::text, 'category', 'Food', 'type', 'EXPENSE', 'amount', 210, 'description', 'Dinner'),
      jsonb_build_object('id', 7, 'userEmail', 'demo@gradflow.local', 'expenseDate', (current_date - 7)::text, 'category', 'Health', 'type', 'EXPENSE', 'amount', 350, 'description', 'Gym day pass'),
      jsonb_build_object('id', 8, 'userEmail', 'demo@gradflow.local', 'expenseDate', (current_date - 6)::text, 'category', 'Coffee', 'type', 'EXPENSE', 'amount', 95, 'description', 'Advisor meeting coffee'),
      jsonb_build_object('id', 9, 'userEmail', 'demo@gradflow.local', 'expenseDate', (current_date - 5)::text, 'category', 'Shopping', 'type', 'EXPENSE', 'amount', 480, 'description', 'Stationery'),
      jsonb_build_object('id', 10, 'userEmail', 'demo@gradflow.local', 'expenseDate', (current_date - 4)::text, 'category', 'Food', 'type', 'EXPENSE', 'amount', 160, 'description', 'Noodles'),
      jsonb_build_object('id', 11, 'userEmail', 'demo@gradflow.local', 'expenseDate', (current_date - 3)::text, 'category', 'Transport', 'type', 'EXPENSE', 'amount', 60, 'description', 'MRT'),
      jsonb_build_object('id', 12, 'userEmail', 'demo@gradflow.local', 'expenseDate', (current_date - 2)::text, 'category', 'Part-time', 'type', 'INCOME', 'amount', 2200, 'description', 'TA support'),
      jsonb_build_object('id', 13, 'userEmail', 'demo@gradflow.local', 'expenseDate', (current_date - 1)::text, 'category', 'Fun', 'type', 'EXPENSE', 'amount', 300, 'description', 'Relax night'),
      jsonb_build_object('id', 14, 'userEmail', 'demo@gradflow.local', 'expenseDate', current_date::text, 'category', 'Food', 'type', 'EXPENSE', 'amount', 190, 'description', 'Lunch')
    ),
    'researchLogs', jsonb_build_array(
      jsonb_build_object('id', 1, 'userEmail', 'demo@gradflow.local', 'logDate', (current_date - 12)::text, 'topic', 'Federated learning survey', 'progress', 'Skimmed three related-work sections.', 'blockers', '', 'nextStep', 'Summarize privacy assumptions.', 'blockerSolved', false, 'nextStepSolved', false, 'hours', 2.0),
      jsonb_build_object('id', 2, 'userEmail', 'demo@gradflow.local', 'logDate', (current_date - 10)::text, 'topic', 'Baseline experiment', 'progress', 'Prepared dataset split and run notes.', 'blockers', 'Need to confirm metric definition.', 'nextStep', 'Ask advisor about evaluation metric.', 'blockerSolved', false, 'nextStepSolved', false, 'hours', 2.5),
      jsonb_build_object('id', 3, 'userEmail', 'demo@gradflow.local', 'logDate', (current_date - 8)::text, 'topic', 'Experiment setup', 'progress', 'Finished initial config and command list.', 'blockers', '', 'nextStep', 'Run small-scale sanity check.', 'blockerSolved', false, 'nextStepSolved', false, 'hours', 3.0),
      jsonb_build_object('id', 4, 'userEmail', 'demo@gradflow.local', 'logDate', (current_date - 6)::text, 'topic', 'Advisor feedback', 'progress', 'Converted feedback into tasks.', 'blockers', '', 'nextStep', 'Draft comparison table.', 'blockerSolved', false, 'nextStepSolved', false, 'hours', 1.5),
      jsonb_build_object('id', 5, 'userEmail', 'demo@gradflow.local', 'logDate', (current_date - 4)::text, 'topic', 'Related work writing', 'progress', 'Outlined paragraph order.', 'blockers', 'Unsure how to contrast paper B.', 'nextStep', 'Write one rough paragraph anyway.', 'blockerSolved', false, 'nextStepSolved', false, 'hours', 1.0),
      jsonb_build_object('id', 6, 'userEmail', 'demo@gradflow.local', 'logDate', (current_date - 2)::text, 'topic', 'Baseline comparison', 'progress', 'Ran first comparison pass.', 'blockers', '', 'nextStep', 'Collect charts for meeting.', 'blockerSolved', false, 'nextStepSolved', false, 'hours', 2.5),
      jsonb_build_object('id', 7, 'userEmail', 'demo@gradflow.local', 'logDate', (current_date - 1)::text, 'topic', 'Error analysis', 'progress', 'Found two suspicious failure cases.', 'blockers', 'Need more examples before conclusion.', 'nextStep', 'Inspect 10 more cases.', 'blockerSolved', false, 'nextStepSolved', false, 'hours', 1.5)
    ),
    'calendarEvents', jsonb_build_array(
      jsonb_build_object('id', 1, 'userEmail', 'demo@gradflow.local', 'title', 'Advisor meeting', 'eventDate', (current_date - 6)::text, 'startDate', (current_date - 6)::text, 'endDate', (current_date - 6)::text, 'startTime', '14:00:00', 'endTime', '15:00:00', 'category', 'Meeting', 'note', 'Discuss experiment direction'),
      jsonb_build_object('id', 2, 'userEmail', 'demo@gradflow.local', 'title', 'Course seminar', 'eventDate', (current_date - 3)::text, 'startDate', (current_date - 3)::text, 'endDate', (current_date - 3)::text, 'startTime', '10:00:00', 'endTime', '12:00:00', 'category', 'Course', 'note', 'Reading response due'),
      jsonb_build_object('id', 3, 'userEmail', 'demo@gradflow.local', 'title', 'Gym session', 'eventDate', (current_date - 2)::text, 'startDate', (current_date - 2)::text, 'endDate', (current_date - 2)::text, 'startTime', '18:30:00', 'endTime', '19:15:00', 'category', 'Health', 'note', 'Run and stretch'),
      jsonb_build_object('id', 4, 'userEmail', 'demo@gradflow.local', 'title', 'Research focus block', 'eventDate', current_date::text, 'startDate', current_date::text, 'endDate', current_date::text, 'startTime', '09:30:00', 'endTime', '11:30:00', 'category', 'Study', 'note', 'Baseline comparison'),
      jsonb_build_object('id', 5, 'userEmail', 'demo@gradflow.local', 'title', 'Budget review', 'eventDate', (current_date + 2)::text, 'startDate', (current_date + 2)::text, 'endDate', (current_date + 2)::text, 'startTime', '20:00:00', 'endTime', '20:30:00', 'category', 'Life', 'note', 'Check weekly expenses')
    ),
    'rewardRedemptions', jsonb_build_array(
      jsonb_build_object('id', 1, 'userEmail', 'demo@gradflow.local', 'reward', jsonb_build_object('id', 1, 'name', 'Coffee break', 'icon', '*', 'pointCost', 4), 'redeemedDate', (current_date - 8)::text, 'pointCost', 4),
      jsonb_build_object('id', 2, 'userEmail', 'demo@gradflow.local', 'reward', jsonb_build_object('id', 1, 'name', 'Coffee break', 'icon', '*', 'pointCost', 4), 'redeemedDate', (current_date - 3)::text, 'pointCost', 4),
      jsonb_build_object('id', 3, 'userEmail', 'demo@gradflow.local', 'reward', jsonb_build_object('id', 2, 'name', 'Movie night', 'icon', '*', 'pointCost', 8), 'redeemedDate', (current_date - 1)::text, 'pointCost', 8)
    ),
    'archivedTasks', jsonb_build_array(),
    'nextIds', jsonb_build_object(
      'goals', 4,
      'habits', 4,
      'rewardItems', 3,
      'tasks', 8,
      'dailyLogs', 14,
      'habitRecords', 34,
      'expenses', 14,
      'researchLogs', 7,
      'calendarEvents', 5,
      'rewardRedemptions', 3
    )
  )::text,
  current_timestamp
)
on conflict (email) do nothing;
